import 'package:hive/hive.dart';

// This line is generated by the build_runner. It will show an error at first.
part 'lock_item.g.dart';

@HiveType(typeId: 0)
class LockItem extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  bool isLocked;

  @HiveField(3)
  DateTime? timestamp;

  @HiveField(4)
  String? photoPath;

  LockItem({
    required this.id,
    required this.name,
    this.isLocked = false,
    this.timestamp,
    this.photoPath,
  });
}